class InitiateFeedbackForm
  include Interactor
  include SlackFormBuilder

  # Initiates the feedback form modal in response to the user's invocation of the /retro-feedback slash command.
  # This interactor is responsible for constructing the necessary payload for the Slack modal and opening it using
  # the provided Slack client.
  # Ref: https://api.slack.com/methods/views.open
  #
  # @example
  #   InitiateFeedbackForm.call(trigger_id: "123", slack_client: Slack::Web::Client.new)
  #
  # @param [String] trigger_id Unique ID generated by Slack when a user invoked slash command /retro-feedback.
  #                            It's used to open the feedback modal response to a user's slash command request.
  # @param [Slack::Web::Client] slack_client An instance of the Slack client for communication.
  # @return [void]
  def call
    @modal_payload = build_modal_payload
    send_modal
  rescue StandardError => e
    log_error(e)
    context.fail!
  end

  private

  def build_modal_payload
    {
      trigger_id: context.trigger_id,
      view: {
        type: "modal",
        callback_id: "feedback_form",
        title: build_title_block,
        submit: build_submit_block,
        close: build_close_block,
        blocks: [
          build_category_block,
          build_comment_block,
          build_anonymous_block
        ]
      }
    }
  end

  def send_modal
    context.slack_client.views_open(@modal_payload)
  end

  def log_error(error)
    error_message = "Error in InitiateFeedbackForm: #{error.message}"
    backtrace = error.backtrace.join("\n")
    Rails.logger.error("#{error_message}\n#{backtrace}")
  end
end
