class InitiateFeedbackForm
  include Interactor
  include SlackFormBuilder

  # Initiates the feedback form modal in response to the user's invocation of the /retro-feedback slash command.
  # This interactor is responsible for constructing the necessary payload for the Slack modal and opening it using
  # the provided Slack client.
  # Ref: https://api.slack.com/methods/views.open
  #
  # If there is no open retrospective, an error message is sent to the user (via DM).
  #
  # @example
  #   InitiateFeedbackForm.call(trigger_id: "123", slack_client: Slack::Web::Client.new, user_id: "123456")
  #
  # @param [String] trigger_id Unique ID generated by Slack when a user invoked slash command /retro-feedback.
  #                            It's used to open the feedback modal response to a user's slash command request.
  # @param [Slack::Web::Client] slack_client An instance of the Slack client for communication.
  # @param [String] user_id The ID of the user who invoked the slash command.
  # @return [void]
  def call
    retrospective = Retrospective.open_retrospective.first
    return no_open_retrospective_message if retrospective.nil?

    @modal_payload = build_modal_payload
    send_modal
  rescue StandardError => e
    log_error(e)
    context.fail!
  end

  private

  def build_modal_payload
    {
      trigger_id: context.trigger_id,
      view: {
        type: "modal",
        callback_id: "feedback_form",
        title: build_title_block,
        submit: build_submit_block,
        close: build_close_block,
        blocks: [
          build_category_block,
          build_comment_block,
          build_anonymous_block
        ]
      }
    }
  end

  def send_modal
    context.slack_client.views_open(@modal_payload)
  end

  def no_open_retrospective_message
    message = "There is no open retrospective. Please run `/retro-open` to open one."
    warning_icon = ":warning:"
    context.slack_client.chat_postMessage(
      channel: context.user_id,
      text: "#{warning_icon} #{message}"
    )
  end

  def log_error(error)
    error_message = "Error in InitiateFeedbackForm: #{error.message}"
    backtrace = error.backtrace.join("\n")
    Rails.logger.error("#{error_message}\n#{backtrace}")
  end
end
