require "rails_helper"

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/retrospectives" do
  # This should return the minimal set of attributes required to create a valid
  # Retrospective. As you add validations to Retrospective, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip("Add a hash of attributes valid for your model")
  end

  let(:invalid_attributes) do
    skip("Add a hash of attributes invalid for your model")
  end

  describe "GET /index" do
    it "renders a successful response" do
      Retrospective.create! valid_attributes
      get retrospectives_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      retrospective = Retrospective.create! valid_attributes
      get retrospective_url(retrospective)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_retrospective_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      retrospective = Retrospective.create! valid_attributes
      get edit_retrospective_url(retrospective)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Retrospective" do
        expect do
          post retrospectives_url, params: { retrospective: valid_attributes }
        end.to change(Retrospective, :count).by(1)
      end

      it "redirects to the created retrospective" do
        post retrospectives_url, params: { retrospective: valid_attributes }
        expect(response).to redirect_to(retrospective_url(Retrospective.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Retrospective" do
        expect do
          post retrospectives_url, params: { retrospective: invalid_attributes }
        end.not_to change(Retrospective, :count)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post retrospectives_url, params: { retrospective: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) do
        skip("Add a hash of attributes valid for your model")
      end

      it "updates the requested retrospective" do
        retrospective = Retrospective.create! valid_attributes
        patch retrospective_url(retrospective), params: { retrospective: new_attributes }
        retrospective.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the retrospective" do
        retrospective = Retrospective.create! valid_attributes
        patch retrospective_url(retrospective), params: { retrospective: new_attributes }
        retrospective.reload
        expect(response).to redirect_to(retrospective_url(retrospective))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        retrospective = Retrospective.create! valid_attributes
        patch retrospective_url(retrospective), params: { retrospective: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested retrospective" do
      retrospective = Retrospective.create! valid_attributes
      expect do
        delete retrospective_url(retrospective)
      end.to change(Retrospective, :count).by(-1)
    end

    it "redirects to the retrospectives list" do
      retrospective = Retrospective.create! valid_attributes
      delete retrospective_url(retrospective)
      expect(response).to redirect_to(retrospectives_url)
    end
  end
end
